#!/bin/sh
SCRIPT=$(readlink -f "$0")
SCRIPTDIR=$(dirname "$SCRIPT")

# Edit these variables to your project settings
PROJDIR=~/Documents/projects
GAMESOURCE=$PROJDIR/mygame
DESKTOP=$SCRIPTDIR/mygame.desktop
ICON=$SCRIPTDIR/mygame.png
IMGDIR=$PROJDIR/MyGame.AppDir
APPIMAGETOOL=/usr/local/bin/appimagetool
OUTFILE=$PROJDIR/MyGame.AppImage
#

TMPDIR=/tmp
GAMEDIR=$IMGDIR/usr/games
APPRUN=$SCRIPTDIR/AppRun

LOVE=/usr/bin/love
CARE=/usr/bin/care
MKDIR=/bin/mkdir
CP=/bin/cp
RM=/bin/rm
CD=/bin/cd
CHMOD=/bin/chmod
if [ ! -d "$IMGDIR" ]; then
$MKDIR $IMGDIR
fi

$CARE -o $TMPDIR/loveframework.tar.gz $LOVE
$CARE -x $TMPDIR/loveframework.tar.gz
$CP -r $SCRIPTDIR/loveframework/rootfs/usr $IMGDIR
$RM -rf $SCRIPTDIR/loveframework
$RM $TMPDIR/loveframework.tar.gz
$CHMOD a+x $APPRUN
$CP $APPRUN $IMGDIR
$CP $DESKTOP $IMGDIR
$CP $ICON $IMGDIR
$MKDIR $GAMEDIR
$CP -r $GAMESOURCE $GAMEDIR
$APPIMAGETOOL $IMGDIR $OUTFILE
$RM -rf $IMGDIR
$CHMOD a+x $OUTFILE
